# Generated by Django 3.1.3 on 2020-11-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201113_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.poll', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
