# Generated by Django 3.1.3 on 2020-11-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_answer_poll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='session_key',
            field=models.CharField(default=1, max_length=200, verbose_name='id анонимного пользователя'),
            preserve_default=False,
        ),
    ]
