# Generated by Django 2.2.10 on 2020-11-12 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
